### ISSUE TITLE
Bold Text

### ISSUE THREAD

**Issue by MggMuggins** [gizmomogwai/colored#1]
How possible would it be to implement bold text? I'm loving how tiny this library is, but lacking just a little basic functionality.

**Comment by gizmomogwai** [comment]
Its totally possible ... i just have to get back from holidays and think about a nice api for that ...

**Comment by gizmomogwai** [comment]
after reading some more how does:
https://stackoverflow.com/questions/2924697/how-does-one-output-bold-text-in-bash
```echo -e "\033[1mSome Text"``` look in your terminal. it might not be possible to implement bold, as it might be rendered bright :)

**Comment by MggMuggins** [comment]
I'm pretty sure it renders as bright. I'm also using fish, so colors are a fun time...

**Comment by gizmomogwai** [comment]
on the flight back i played around with styles ... will post this version soon

**Comment by gizmomogwai** [comment]
please have a look, if thats how you would like to access styles.
if you cannot check it by source, i can also push a tag, which results in a new dub package.

**Comment by MggMuggins** [comment]
If you could push a tag I'd appreciate it.

**Comment by gizmomogwai** [comment]
tag is pushed .. should be available as a new version from http://code.dlang.org/packages/colored/0.0.6

**Comment by MggMuggins** [comment]
Danke Danke... Testing now.

My guess is that things worked, just Konsole does interesting things with bold text... Kudos for a quick addition!

**Comment by gizmomogwai** [comment]
yeah .. its quite interesting what is supported by which terminal ... the link i took inspiration from:
https://misc.flogisoft.com/bash/tip_colors_and_formatting mentions what terminal supports which styles ... xterm e.g. does even blinking :))

**Comment by MggMuggins** [comment]
I love how simple your library is, so kudos. If I need color, this is where I will go 👍

**Comment by gizmomogwai** [comment]
Thanks a lot ... thats why I did it, there are a few more out there, that are bigger, take longer to compile and do more (which I do not need). Still I am not sure, if the escape sequences that I create are "optimal", but on the other hand side, I do not think that it really matters, because terminals are fast enough :)
